### ISSUE TITLE
Cant delete games

### ISSUE THREAD

**Issue by h2359** [ifrotz/iosfrotz#264]
hi i have an iphone 5s running ios [8.4 and i am using the lateist version of the frotz app and i also use voiceover and i was wondering how to delete games from the story list
When i am in the list their is no edit or delete buttons anywhere i hope you can help mePlease glance at the existing issues to make sure the problem you are
reporting  isn't a known issue before reporting.  Feel free to remove or
edit any parts of the form template which don't apply to your issue.]
D

What steps will reproduce the problem?
1.
2.
3.

What is the expected output or behavior?  What do you see instead?

What version of Frotz are you using?
1.7.1

What device model are you using (e.g., iPhone 6, iPad 4, iPod Touch 4th gen.)
iPhone 6

What version of iOS?  (6.1, 7.0, etc.)
8.3

Please provide any additional information below.

**Comment by ifrotz** [comment]
If the game is still active, that is, it is the game which resumes if you press "Now Playing",  which is the top item in the Recently Played heading, then you must quit the game first.

Otherwise, you can delete a story/game with Voiceover enabled by tapping on the game in the Story List, swiping up once (it should say "Delete") then double tapping.

**Comment by h2359** [comment]
This seems to have worked thanks so much for your help
