### ISSUE TITLE
Using public namespace for UTI undefined

### ISSUE THREAD

**Issue by MaddTheSane** [ifrotz/iosfrotz#265]
According to [Apple's documentation](https://developer.apple.com/library/ios/documentation/General/Conceptual/DevPedia-CocoaCore/UniformTypeIdentifier.html):

> UTIs in the `public` domain are defined by Apple and are used to represent common formats.

I noticed that iFrotz's UTIs are in the `public` domain. Perhaps `com.flippencorp` could be used for the domain instead?

**Comment by ifrotz** [comment]
It's true that these are not standard Apple-defined UTIs.
But using com.flippencorp wouldn't be right either, since Frotz doesn't define the file formats; they are open standards used by all interpreters. 
I used them because existing interpreters for the Mac (such as Zoom, Gargoyle, and Spatterlight) already use these UTIs in the "public." namespace to refer to various IF-related file formats.  I used the same UTIs as they did for the same file formats.

So I won't be changing them against Apple objects.
