### ISSUE TITLE
Crash with iOS 9 and multitasking

### ISSUE THREAD

**Issue by jmmelko** [ifrotz/iosfrotz#274]
Hi,

since I updated to iOS 9.x switching to another app and then going back to Frotz make it to crash. Hopefully Frotz saves the current state so by relaunching it I can go on where I left it.
very annoying tough.

Please see the attached log files for more information.

Tell me if there is something I can do to help you with diagnosis.

[FrotzCrash.zip](https://github.com/ifrotz/iosfrotz/files/117790/FrotzCrash.zip)

tx.

**Comment by PeterPiers** [comment]
(this is probably the same issue as 271)

I'm not the dev, just FYI, but I'm interested, When you go back to Frotz, does it look as though it's restarting? When you switch between apps, if one of the apps is very intensive or stays open for a long time I've found that switching back to a previous app is effectively the same as opening it from scratch again. Is this the stage at which it crashes? (in which case it may be related to issue 272)

Or does it look as though it's going back to a functioning iFrotz, still open where you left it? Can you see whether the cursor line is blinking? Issue 271 reports that the crash didn't happen until you tried to type in a command, is that what's also happening to you?

Note to Craig - I haven't seen this happen, but if you'll recall, I'm using a slightly different build, so my experience won't help much here! Even though I'm also using iOS 9.x.

**Comment by ifrotz** [comment]
Yes, this does appear to be the same as #271.  This issue appears to be caused a bug in Apple's SDK compatibility.
Just building Frotz with a newer SDK makes the issue disappear, which is why it does't happen in your build, Peter.  The current Frotz on the App Store still supports devices all the way back to the original iPhone running iOS 3, which means it has to be built with an older SDK, but as time goes on Apple seems to be less and less concerned about breaking compatibility with older apps.

Apple semi-recently started allowing users on old devices to download older versions of apps if the latest updates are no longer compatible, so in next release of Frotz, I will drop support for anything before iOS 7.  This will allow me to use the newer SDK and address this problem.  I don't have an ETA but it'll probably be in spring or early summer.

Sorry for the inconvenience in the mean time.  Frotz does save your gave state automatically so you shouldn't lose any progress from the crashes.

**Comment by PeterPiers** [comment]
Thanks for the feedback! Good to know this is a temporary setback and already due to be easily sorted with the next release.

**Comment by jmmelko** [comment]
In response to Peter : yes the crash happens when I try to type a command.

Thank you to the dev for his detailed answer. IFrotz is unique!

**Comment by Lwio** [comment]
I was using Frotz and the iPod touch froze. I had to restart the device. It could be related to this error. This device hasn't froze yet, got at Christmas so guessing it's Frotz. Thanks for the work btw.

**Comment by spathiwa** [comment]
Fixed by rebuilding with later SDK. 52be67b8

**Comment by spathiwa** [comment]
Fixed in 1.8 in App Store.
