### ISSUE TITLE
Trouble building out of the box

### ISSUE THREAD

**Issue by glangmead** [ifrotz/iosfrotz#288]
On a fresh git clone, macOS 10.13.2, Xcode 9.2, I ran into a few issues preventing building

- tads, ftpservlib, and some others failed to find "iosfrotz.h" in include/ and "ifrotzdefs.h" in ui/. Adding include/ and ui/ to the search paths resolved this

- link error I'm looking into:

ld: warning: directory not found for option '-F/Users/craig/Desktop/Reveal.app/Contents/SharedSupport/iOS-Libraries'
ld: library not found for -lPods-Frotz
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by glangmead** [comment]
I see that Reveal is a third party debugging tool and I don't have that, but that's just a linker warning. The actual error is about Pods-Frotz which I don't know what is.

**Comment by spathiwa** [comment]
Sorry for leaving things in a bad state.

DropBox discontinued support for their old API forcing me to upgrade Frotz to allow DropBox syncing to continue working, and the iOS libraries for the newer API version of it were built using CocoaPods, a Ruby-based module/dependency system.  

It has some generated files that are not meant to be checked into source code control, and you’re supposed to install CocoaPods and run  a command to update deps, but  I attempted to make the build scripts robust in the face of CocoaPods not being installed so that it would automatically just build without DB support in that case, but it looks like I failed.

I won’t have time until this evening to look into the issue, but I *think* you can turn off the ifdef for DB support and uncheck the link reference to the Pods-Frotz and it might work.

**Comment by glangmead** [comment]
Oh I hadn't used Cocopods before, so I installed it and have everything building now, with a couple minor patches:

diff --git a/ui/StoryMainViewController.m b/ui/StoryMainViewController.m
index 3332e16..ea0f9c6 100644
--- a/ui/StoryMainViewController.m
+++ b/ui/StoryMainViewController.m
@@ -4549,6 +4549,7 @@ -(NSString*)completeWord:(NSString*)str prevString:(NSString*)prevString isAmbig
 static NSString *kDefaultDBTopPath = @"/Frotz";
 
 static BOOL migateDropboxAuth() {
+#ifdef FROTZ_DB_APP_KEY
 #if UseNewDropBoxSDK
     BOOL willPerformMigration = [DBClientsManager checkAndPerformV1TokenMigration:^(BOOL shouldRetry, BOOL invalidAppKeyOrSecret,
                                                                                     NSArray<NSArray<NSString *> *> *unsuccessfullyMigratedTokenData) {
@@ -4584,6 +4585,7 @@ static BOOL migateDropboxAuth() {
 #else
     return NO;
 #endif
+#endif
 }
 
 #if UseNewDropBoxSDK
diff --git a/Podfile b/Podfile
index 84ebdfe..47cf0ac 100644
--- a/Podfile
+++ b/Podfile
@@ -1,4 +1,4 @@
-platform :ios, '8.0'
+platform :ios, '9.0'
 
 target 'Frotz' do
     pod 'ObjectiveDropboxOfficial'

**Comment by spathiwa** [comment]
Fixed in 1.8.4 (I think).
