### ISSUE TITLE
Frotz does not fill screen on new iPhones (X, XS, XS Max, XR)

### ISSUE THREAD

**Issue by simiadei** [ifrotz/iosfrotz#292]
What steps will reproduce the problem?
Problem is apparent immediately upon launching the app on an X-series iPhone.

What is the expected output or behavior?  What do you see instead?
Expected: App window extends to top and bottom of screen.
Actual: App window does not fill entire screen, leaving blank space at top and bottom.

What version of Frotz are you using?
1.8.2

What device model are you using?
iPhone XR

What version of iOS?
12.1.2

**Comment by alanshutko** [comment]
It looks like this just needs a recompile with Xcode 10 to make it happen.  At the same time, I also think the deployment target needs to be upgraded to iOS 9, since that's what the dropbox pod requires. I'm going to try it locally and see if I can do a PR.

**Comment by spathiwa** [comment]
Someone has already put in a pull request with this change.
I had also done it myself a while back, but had other changes mixed in with that I had hoped to finish as well before putting out an update.  I just have been busy with my real job and haven't found the time to push through a Frotz release due to the hassle involved (making screenshots appropriately sized for all existing devices, dealing with new App Store requirements).  I hope to get to it soon.

**Comment by simiadei** [comment]
Good to hear it's in the pipeline. Thanks for maintaining this great app; it was the very first iOS game I downloaded way back in 2008 and it's been on all my devices since.

**Comment by kimsand** [comment]
If you simply do not have the time to work on this, is there any chance you can allow others to help out with at least the pull requests?

**Comment by simiadei** [comment]
please... I've waited so long.........

**Comment by simiadei** [comment]
please... ;_;

**Comment by spathiwa** [comment]
Fixed (finally) in 1.8.4.

**Comment by simiadei** [comment]
Thank you!
