### ISSUE TITLE
ios13 crash

### ISSUE THREAD

**Issue by the7pizzas** [ifrotz/iosfrotz#298]
Frotz crashes on ios13 no problem prior to update ios13. Crashes a lot when trying to launch a game. 

What steps will reproduce the problem?
1. Open app in ios13 and launch game
2.
3.

What is the expected output or behavior?  What do you see instead?

What version of Frotz are you using?
1.8.2

What device model are you using (e.g., iPhone 6, iPad 4, iPod Touch 4th gen.)
iPhone 6s

What version of iOS?  (6.1, 7.0, etc.)
13

Please provide any additional information below.

Voiceover is on when using app to see screen and type in commands

**Comment by spathiwa** [comment]
I can't seem to reproduce this, but I was only able to try using iOS 13.1.  
Does the issue happen for all games or specific game(s)?  If so, please specify which.
Please try upgrading to iOS 13.1 and see if the issue still occurs.  If it does, I can attempt to reproduce the issue on an iPhone 6s or as close as I can locate, but we should rule out specific game and iOS version differences first.  Thanks.

**Comment by spathiwa** [comment]
Make that 13.1.1, which apparently is out already.

**Comment by the7pizzas** [comment]
I already updated to ios13.1.1 The issue isn’t as frequent as it was, however it is still present.

**Comment by spathiwa** [comment]
Ok, so if a game doesn't crash at launch, does it play fine until you launch again?  Or does it crash randomly during play?
Please give a specific game you are playing, it would help reproduce.

**Comment by the7pizzas** [comment]
It happens with every game. Usually after: a. I have played through 1 or 2 games or: b. I open 1 or 2 games, decide I’m not in the mood to play said games and then launch game number 2/3

**Comment by the7pizzas** [comment]
I am currently playing 9:05, Curses and Act of Misdirection

**Comment by the7pizzas** [comment]
Just giving an update on something that might be helpful for reproducing the issue. I am blind and use voiceover. I have had help from a few people who consistently get the app to launch a game without crashing. It has been suggested that voiceover may be the issue.

**Comment by spathiwa** [comment]
I found some crash dump logs having to do with accessibility/voiceover that I think are the same issue you are hitting and will help debug it.  Frotz has custom text output view-controllers because it was written before Apple provided good rich text support in their APIs, so I had to implement accessibility support for this myself.  It looks like something has changed with the order functions are called so that when you switch games, it's using a stale value which tells it the index of the last accessibility item (text snippet) announced, which overflows an array if the game you are switching to has fewer output text paragraphs than the one you're switching from.
Sorry, that's probably too, technical, but it means you might be able to avoid crashes by scrolling to the top of the output and tapping to announce some older text before you go back to the menu to switch games.
Fortunately, since the crash happens at game launch, it doesn't involve any loss of progress.  I should be able to fix it in the next update.

**Comment by the7pizzas** [comment]
Thanks so much.

**Comment by the7pizzas** [comment]
Just updated to ios13.2. It appears the crashing has stopped.
