### ISSUE TITLE
Saving fails in many games, after the latest update.

### ISSUE THREAD

**Issue by Leettyun** [ifrotz/iosfrotz#305]
After the latest update, saving appears to fail in many, if not all, games, including Curses, Worlds Apart, and Zozzled. In Worlds Apart, the saving process fails on the first move, however, in Curses, the problem starts after the player receives there first points, and, in Zozzled, it begins after the player selects there choice, at the very beginning of the game.

**Comment by spathiwa** [comment]
Sorry about this.  I'm working on a fix, wish I will submit tonight and should be published tomorrow or Saturday unless there is a delay in reviewing because of the holiday.
I was in a rush to get the update out before Apple started removing apps that weren't using the iOS 13 SDK.
All of my testing had a hardware keyboard connected, and this bug occurs when you do not (which alas, is most of the time for most people).

**Comment by spathiwa** [comment]
The fix is submitted and awaiting App Review.  Sorry for the inconvenience.

**Comment by spathiwa** [comment]
Looks like you closed this before the fix was even available, I just got the notice it was out of review and released i a few minutes agot.
Anyway, update to 1.8.4. and you should be good now.  Sorry again for the trouble.
