### ISSUE TITLE
Slouching towards bedlam.gblorb fails to run

### ISSUE THREAD

**Issue by AdamTheLang** [ifrotz/iosfrotz#311]
Latest version of Slouching Towards Bedlam crashes when you attempt to run it with three error messages: can’t read data, “it seems to be corrupted”, and “unknown error occurred”.

**Comment by turki0l0** [comment]
> Latest version of Slouching Towards Bedlam crashes when you attempt to run it with three error messages: can’t read data, “it seems to be corrupted”, and “unknown error occurred”.

**Comment by spathiwa** [comment]
It appears that the site which hosts this file linked to by IFDB is sluggish and prone to returning truncated files.
After failing to reproduce this a while back, I tried again on a different device and the download appeared to hang, and when I tried to run the game it crashed similar to what you described, but it turns out the file really is corrupt.  Trying the download again fixed it.
