### ISSUE TITLE
Frotz not showing up in Share Sheets

### ISSUE THREAD

**Issue by Calorion** [ifrotz/iosfrotz#315]
I'm trying to import a .ZIP file into Frotz, but it's not showing up as an extension, either under "apps" or "actions."

iPad Pro 10.5", iPadOS 14.7.1

**Comment by Calorion** [comment]
Ah. "ZIP" is not supported, for some reason. Why not?

**Comment by spathiwa** [comment]
If you mean the historical Infocom usage of .zip as Z-machine version 3 (modern .z3), then I think supporting that would be confusing for users who expect .zip to have the normal, world-standard meaning.  Just rename the file.

If you want it to be able to open .zip archives launched from other apps, I think there is also some potential for confusion if Frotz were registered as a file handler for arbitrary zips, since it only understands story formats embedded in zip files.
I think it's better to go through a general zip handling app like Files, extract the files you want, and then pass to Frotz to avoid the confusion of showing up in the action sheet for any .zip file of any content.

You can still browse to the location of the zip directly in Frotz's IFDB web browser, and it will open the zip, and, new in 1.8.7, allow you to select individual stories to extract instead of automatically doing all of them.
