### ISSUE TITLE
Hiding the keyboard on iPad

### ISSUE THREAD

**Issue by snan** [ifrotz/iosfrotz#317]
On Frotz 1.8.6 on iPad OS 16.2, how do I hide the keyboard so I can play using the shortcuts instead? I can see how there's a popup menu of common words and I can click on on screen words. Long-pressing the keyboard button in the top right does nothing.

And if it's possible to hide, how do I hit return to send the commands?

**Comment by spathiwa** [comment]
You are supposed to be able to long press the keyboard button to lock the keyboard as hidden, but it appears something in recent iOS updates has broken that functionality and no one had reported it/discovered it.

I’m working on an update that I hope to push out within the next few weeks so I’ll add that to my to-do list.

After entering a command via the shortcuts, you can swipe up on the command line to simulate pressing enter.  On an iPad with smaller fonts, the tap target area for the command line is a little small so that’s probably a usability issue, but you can do it with practice.   I should probably add an explicit button.

As far as a notes area, you can swipe to the left to reveal a full-screen notepad (which is maintained per story).

Craig

**Comment by spathiwa** [comment]
This functionality is restored in version 1.8.7 now in the App Store.

Fixed in commit 6a8a25be78.

**Comment by spathiwa** [comment]
Closing.
