### ISSUE TITLE
bluetooth keyboard arrow keys no longer work after app update.

### ISSUE THREAD

**Issue by Razzb3rrie** [ifrotz/iosfrotz#319]
hello! when the update came out i noticed it right away, i left a review on the apple store mentioning this and im not sure if it has been seen. i really do love this app but without the arrow keys i am unable to play my stories ans i have been unsuccessful in finding any alternatives as good as this! im really hoping this is seen and looked at. im positive it was a recent update that changed this as i have auto update turned off and back in august, i had accidentally updated the app and it stopped working. it was working perfectly fine before it was updated. i really hope this bug gets fixed! 

if theres any way to fix this or any information on why it no longer works i would really appreciate if someone replied and let me know! 

<3

**Comment by spathiwa** [comment]
Hi there. 
Sorry I didn't notice your review.  I only actively monitor reviews for bugs during the first few weeks after a new version. The update was 5 months ago even though you only installed it in August.  It's always best to report bugs directly here rather than in a review. 

It looks like arrow keys stopped working because Apple made a change in the iOS 15 SDK so you have to explicitly configure keyboard shortcuts in your app to declare that they want to override system key bindings if they conflict, and arrow up and down by default move the cursor to the beginning and end of the line, respectively. They also started forcing devs to submit apps with the latest SDK, which otherwise I would've been protected from arbitrary breaking changes like this by just continuing to use an older SDK. 

Anyway, sorry for the inconvenience.  It looks like the fix is pretty simple.  I'll try to find some time to implement it and push out an update this weekend, if not, within the next couple weeks.

**Comment by spathiwa** [comment]
This has been fixed in 1.8.8, now in the App Store.
